services:
    web:
      container_name: web
      build:
        dockerfile: ./compose/pndconsole/Dockerfile
      entrypoint: 
        - /usr/src/app/web-entrypoint.sh
      environment:
        DJANGO_SUPERUSER_PASSWORD: "admin"
      ports:
        - "8000:8000"
      depends_on:
        - db

    daphne:
        container_name: daphne
        build:
          dockerfile: ./compose/pndconsole/Dockerfile
        entrypoint:
          - /usr/src/app/daphne-entrypoint.sh
        ports:
           - "8001:8001"
        depends_on:
          - db
          - web
    
    celery-worker:
      container_name: worker
      build:
        dockerfile: ./compose/pndconsole/Dockerfile
      entrypoint:
          - /usr/src/app/worker-entrypoint.sh
      depends_on:
        - db
        - web

    celery-beat:
      container_name: beat
      build:
        dockerfile: ./compose/pndconsole/Dockerfile
      entrypoint: 
        - /usr/src/app/beat-entrypoint.sh
      depends_on:
        - db
        - web

    telegram:
        build:
          context: ./src/telegram
          dockerfile: ../../compose/telegram/Dockerfile
        volumes:
          - ./src/telegram/known.json:/usr/src/app/known.json
        depends_on:
          - web

    db:
      image: postgres:15
      volumes:
        - pg_data:/var/lib/postgresql/data/
      # The values chosen here must be reflected in src/pndconsole/pndconsole/config.ini
      environment:
        - POSTGRES_USER=POSTGRES_USER
        - POSTGRES_PASSWORD=POSTGRES_PASSWORD
        - POSTGRES_DB=POSTGRES_DB_NAME

    redis:
      image: redis:6.0.16-alpine
      restart: always
      container_name : redis
      ports:
        - "6379:6379"

volumes:
  pg_data:


